---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: ''
public_path: https://res.cloudinary.com/maxgoldhouse/image/upload
front_matter_path: https://res.cloudinary.com/maxgoldhouse/image/upload
use_front_matter_path: true
file_template: ":filename:"
